name: GitHub Actions Demo
on: [push]
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running validation"
  Scan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running code scanning"
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running build"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy"