name: GitHub Actions Demo
on: [push]
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running validation"
  Build:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - run: npm --version
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy"